name: Qodana Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main
      - bks
  workflow_dispatch:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Qodana Scan
        id: qodana_scan
        uses: JetBrains/qodana-action@v2024.1
        with:
          args: -e,ORG_GRADLE_PROJECT_onstructiveUsername=${{ secrets.M2_USER }},-e,ORG_GRADLE_PROJECT_onstructivePassword=${{ secrets.M2_PWD }}

          pr-mode: false
          push-fixes: pull-request
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

      - name: Debug Qodana Output
        if: ${{ failure() }}
        run: |
          echo "Qodana scan failed with exit code ${{ steps.qodana_scan.exit-code }}"
          # Add additional debugging commands here if needed
